# Payment status
PAYMENT_PENDING = 1
PAYMENT_FINISHED = 2
PAYMENT_FAILED = 3

# Subscription status
SUBSCRIPTION_ACTIVE = 1
SUBSCRIPTION_INACTIVE = 2

# Payment log status
LOG_PENDING = 0
LOG_SUCCESS = 1
LOG_FAILED = 2

EVENT_PAYMENT_CREATED = 1
EVENT_PROVIDER_REQUEST_SENT = 2
EVENT_PROVIDER_PAYMENT_ACCEPTED = 3
MESSAGE_BROKER_MESSAGES = 4